### ISSUE TITLE
mobx如何跨页面传递数据啊？

### ISSUE THREAD

**Issue by zeybar** [OrangeXC/gank#27]
比如说导航栏有个登录状态，如果在每个页面都知道它的登录状态，如果不用cookie的话

**Comment by OrangeXC** [comment]
@zeybar 就你的问题描述来看，你需要了解下**全局状态管理**相关的东西，这其中至于使用 redux 还是 mobx 不是重点，相关教程和文章很多，开源项目也很多，我在这就不给你一一举例了

**Comment by william-xue** [comment]
线上好像 访问不了 不过不影响
